### ISSUE TITLE
看到别人用actions/upload-release-asset用着不错

### ISSUE THREAD

**Issue by ClayMoreBoy** [kang-mk/Beta-OpenWrt-AutoBuild#1]
[https://github.com/lisaac/luci-app-diskman/blob/master/.github/workflows/build.yml](url)
IPK编译好直接发布release
[https://github.com/williambj1/OpenCore-Factory/blob/master/azure-pipelines.yml](url)
每日发布

看下怎么把两个yml融合一下固件(打包好的)每日计划编译也发布release

**Comment by ClayMoreBoy** [comment]
已经找到相关脚本 [https://github.com/search?q=openwrt+actions%2Fupload-release-asset&type=Code](url)

**Comment by kang-mk** [comment]
之前考虑过这个问题，但是因为我有时候需要手动发布release来触发编译任务，跟自动发布release会产生冲突，而且我是完全自己用的固件，没必要搞那么麻烦，也就放弃了
